In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.4.1

In [2]:
n_rows = 365 * 24 
n_cols = 2         
cols = ['col1', 'col2'] 

df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), columns=cols)

df.index = pd.date_range(start='2023-01-01', periods=n_rows, freq='h')

df.head()

                     col1  col2
2023-01-01 00:00:00    13    13
2023-01-01 01:00:00     9    19
2023-01-01 02:00:00    19     9
2023-01-01 03:00:00    10     6
2023-01-01 04:00:00     3    10

In [3]:
df.resample('M')['col1'].sum().to_frame()

C:\Users\S. Yabestian\AppData\Local\Temp\ipykernel_23324\985753190.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df.resample('M')['col1'].sum().to_frame()

            col1
2023-01-31  7358
2023-02-28  6724
2023-03-31  7386
2023-04-30  7468
2023-05-31  7432
2023-06-30  7329
2023-07-31  7471
2023-08-31  7406
2023-09-30  7334
2023-10-31  7426
2023-11-30  6913
2023-12-31  7564

In [4]:
df.resample('D')['col1'].sum().to_frame()

            col1
2023-01-01   241
2023-01-02   245
2023-01-03   279
2023-01-04   262
2023-01-05   233
...          ...
2023-12-27   225
2023-12-28   269
2023-12-29   250
2023-12-30   292
2023-12-31   257

[365 rows x 1 columns]

In [5]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.4.1

In [6]:
pd.DataFrame({'col1':[1, 2, 3, 4], 
              'col2':[5, 6, 7, 8]})

   col1  col2
0     1     5
1     2     6
2     3     7
3     4     8

In [7]:
n_rows = 5
n_cols = 3

arr = np.random.randint(1, 20, size=(n_rows, n_cols))
arr

array([[14,  6, 15],
       [ 2, 15, 13],
       [ 1,  3,  6],
       [ 9, 13, 16],
       [15, 13,  7]], dtype=int32)

In [8]:
pd.DataFrame(arr, columns=tuple('ABC'))

    A   B   C
0  14   6  15
1   2  15  13
2   1   3   6
3   9  13  16
4  15  13   7

In [9]:
n_rows = 30 
n_cols = 4 
columns = list('ABCD')

data = np.random.randn(n_rows, n_cols)

df = pd.DataFrame(data, columns=columns)

print(df.head())

          A         B         C         D
0 -0.107976  0.079116 -0.218767  1.135832
1 -0.613556 -1.435032  1.655319 -0.686395
2 -0.645892 -0.189629 -0.586084 -1.549123
3 -0.769560 -1.683705  0.740739 -2.295850
4 -0.300522 -1.594573  1.192419 -0.186827

In [10]:
n_rows = 5 

data = {
    'A': np.random.randn(n_rows),                 
    'B': np.arange(1, n_rows + 1),                
    'C': pd.date_range('2024-01-01', periods=n_rows), 
    'D': ['foo', 'bar', 'baz', 'qux', 'quux']    
}

df = pd.DataFrame(data)

print(df.head())

          A  B          C     D
0 -0.925657  1 2024-01-01   foo
1  1.683836  2 2024-01-02   bar
2 -0.107576  3 2024-01-03   baz
3  0.074191  4 2024-01-04   qux
4  0.745726  5 2024-01-05  quux

In [11]:
n_rows = 30  
n_cols = 4   
columns = list('ABCD')  

time_index = pd.date_range(start='2024-01-01', periods=n_rows, freq='D')  

df = pd.DataFrame(np.random.randn(n_rows, n_cols), index=time_index, columns=columns)

print(df.head())

                   A         B         C         D
2024-01-01  1.351151 -1.002584 -1.779221 -2.267579
2024-01-02 -0.630278 -1.315452  0.308251  2.758396
2024-01-03 -0.482838  0.220914  0.119842  0.151981
2024-01-04  0.987779  0.056100 -0.120131  0.428136
2024-01-05  0.946218 -0.481152  0.424169 -2.279325

In [12]:
n_rows = 5
n_cols = 4

data = np.random.randn(n_rows, n_cols)

df = pd.DataFrame(data, columns=list('ABCD'))

df.iloc[0, 1] = np.nan
df.iloc[2, 3] = np.nan
df.iloc[4, 0] = np.nan

print(df.head())

          A         B         C         D
0 -0.570470       NaN  0.125088 -0.453278
1 -0.591556 -0.195750 -0.234564 -0.427988
2 -0.692996 -1.698491  1.002508       NaN
3 -1.308382 -0.350164  0.194492 -0.269726
4       NaN  1.615618  1.150508 -1.950721

In [13]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.4.1

In [14]:
n_rows = 5
n_cols = 2
cols = ['omset', 'operasional']

df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), 
                  columns=cols)
df

   omset  operasional
0      3            6
1      3            3
2     16           10
3     19            3
4     11            8

In [15]:
df['omset'] = df['omset'] * 100_000
df['operasional'] = df['operasional'] * 10_000
df

     omset  operasional
0   300000        60000
1   300000        30000
2  1600000       100000
3  1900000        30000
4  1100000        80000

In [16]:
n_rows = 365  

df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, 2)), columns=['col1', 'col2'])

df.index = pd.date_range(start='2024-01-01', periods=n_rows, freq='D')

df = df.reset_index().rename(columns={'index': 'tanggal'})

print(df)

       tanggal  col1  col2
0   2024-01-01    19    15
1   2024-01-02    18    12
2   2024-01-03     6     4
3   2024-01-04    18    15
4   2024-01-05     6    14
..         ...   ...   ...
360 2024-12-26    13     9
361 2024-12-27     6     6
362 2024-12-28     6    18
363 2024-12-29     5    13
364 2024-12-30    19    11

[365 rows x 3 columns]

In [17]:
formatku = {'tanggal':'{:%d/%m/%y}', 
            'operasional':'Rp {:.2f}',
            'omset':'Rp {:.2f}'}

laporan = df.style.format(formatku)
laporan

AttributeError: The '.style' accessor requires jinja2

In [18]:
type(laporan)

NameError: name 'laporan' is not defined

In [20]:
Laporan.set_caption('Data Omset dan Operasional')

NameError: name 'Laporan' is not defined

In [21]:
import pandas as pd

print(pd.__version__)

2.3.3

In [22]:
d1 = {'col1':[1, 2, 3], 
      'col2':[10, 20, 30]}
df1 = pd.DataFrame(d1)
df1

   col1  col2
0     1    10
1     2    20
2     3    30

In [23]:
d2 = {'col3':[4, 5, 6], 
      'col4':[40, 50, 60]}
df2 = pd.DataFrame(d2)
df2

   col3  col4
0     4    40
1     5    50
2     6    60

In [24]:
df = pd.merge(df1, df2, left_index=True, right_index=True)
df

   col1  col2  col3  col4
0     1    10     4    40
1     2    20     5    50
2     3    30     6    60